import Image from "next/image";
import "./globals.css";
import './css/default.css';
import './front/css/scroll.css';
import './front/css/reset.css';
import './css/common.css';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
function Header(){
  return (
    <header className="header">
      <div className="w1600">
        <div className="logo">
          <Image src="/img/common/logo.png" alt="logo" width={195} height={34} />
        </div>
        <h5 className="center_tit">DENIAL OF NEGATIVITY</h5>
        <div className="menu_btn">
          <span className="line line1"></span>
          <span className="line line2"></span>
          <span className="line line3"></span>
        </div>
      </div>
    </header>
  )
}
function Footer(){
  return (
    <footer className="footer">
      <div className="w1600">
        <div className="txt_wrap">
          <h5>GAINSAYER</h5>
          <p>
            Our brand turns doubt and chaos into bold streetwear, blending oversized silhouettes<br />
            and graphic details into limited collections that embody rebellion and individuality.
          </p>
        </div>
        <div className="ft_logo">
          <Image src="/img/common/logo.png" alt="ft_logo" width={195} height={34} />
        </div>
      </div>
    </footer>
  )
}
