import Image from "next/image";
import "./globals.css";
import './css/default.css';
import './front/css/scroll.css';
import './front/css/reset.css';
import './css/common.css';
import Symbol from "./components/Symbol";
import LenisScroll from "./components/LenisScroll";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body>
        <LenisScroll>
          <Header />
          {children}
          <Footer />
        </LenisScroll>
      </body>
    </html>
  );
}
function Header(){
  return (
    <header className="header">
      <div className="w1600">
        <div className="logo">
          <Image className="pc_logo" src="/img/common/logo.png" alt="logo" width={195} height={34} />
          <div className="m_logo">
            <Symbol />
          </div>
        </div>
        <h5 className="center_tit pc_tit">DENIAL OF NEGATIVITY</h5>
        <h5 className="center_tit m_tit">
          <span className="reverse_y_text">G</span>
          <span>A</span>
          <span>I</span>
          <span>N</span>
          <span className="reverse_y_text">S</span>
          <span>A</span>
          <span>Y</span>
          <span>E</span>
          <span className="reverse_y_text">R</span>
        </h5>
        <div className="menu_btn">
          <span className="line line1"></span>
          <span className="line line2"></span>
          <span className="line line3"></span>
        </div>
      </div>
    </header>
  )
}
function Footer(){
  return (
    <footer className="footer">
      <div className="w1600">
        <div className="txt_wrap">
          <h5>GAINSAYER</h5>
          <p>
            Our brand turns doubt and chaos into bold streetwear, blending oversized silhouettes<br />
            and graphic details into limited collections that embody rebellion and individuality.
          </p>
        </div>
        <div className="ft_logo">
          <Image src="/img/common/logo.png" alt="ft_logo" width={195} height={34} />
        </div>
      </div>
    </footer>
  )
}
